### ISSUE TITLE
Publish a new version in the marketplace

### ISSUE THREAD

**Issue by PierreZ** [foundationdb-rs/foundationdb-actions-install#4]
When #1, #2, #3 are done, we can publish a new version to the marketplace.

We need to be careful around the naming, as they need to be unique. This means we cannot use the `Install foundationdb` name because it is owned by Clikengo.

![Screenshot from 2022-01-06 07-51-55](https://user-images.githubusercontent.com/2698318/148343339-29de87a6-0351-4c4f-9b89-aefde1dc7dee.png)

We could change to something like `Setup FoundationDB`, what do you think?

## Todos

- [x] close #1, #2, #3
- [x] #7
- [x] create tag and release(I guess `2.0.0` is good)
- [x] publish on the Marketplace

**Comment by khouari1** [comment]
`Setup FoundationDB` sounds good to me 👍

**Comment by PierreZ** [comment]
I also like `Setup FoundationDB` :+1:
